////Brian Witte
////FINAL
////BAM, CST Mon 6-9

////GROUND////
float horizon;
////HEIGHT RANGE////
float hmin, hmax;
//float q=(hmax-hmin)/2;
////WEIGHT RANGE////
float wmin, wmax;
//float r=(wmax-wmin)/2;
////Number of people generated by our array for the sameple size.  
int many= 10;
int a=many;
Person[] people = new Person[many];
int many2=11;
Person[] bri= new Person[many];
String[] names = {"Anita", "Cathy", "Chad", "Dan", "David", "Elizabeth", "Enrique", 
"Erona", "Gordon", "Greg", "Jennifer", "Jill", "Kathy", "Kim", "Kirk", "Mark", 
"Melissa", "Mina", "Mitch", "Narie", "Sabita", "Roberta", "Ryan", "Scott"};
/*int z[]= {"Anita", "Cathy", "Chad", "Dan", "David", "Elizabeth", "Enrique", 
"Erona", "Gordon", "Greg", "Jennifer", "Jill", "Kathy", "Kim", "Kirk", "Mark", 
"Melissa", "Mina", "Mitch", "Narie", "Sabita", "Roberta", "Ryan", "Scott"};
*/

String who[]={ "Kim", "Kirk", "Mark", 
"Melissa", "Mina", "Mitch", "Narie", "Sabita", "Roberta", "Ryan", "Scott" };


////this is where I am making the new array of people
Button buttons[]=new Button[5];
int numButtons=3;
//This string will allow me to have a pool of names to pick from for the buttons, just like the stat subjects.
String buttonNames[]= {  "Raise", "Bonus", "Change"};
float total;
float raise;
int salary;
int age;
int bonus = 1000;
void setup(){
  
  size(750,550);
  
  horizon = height/1.5;
  
  ////The people's sizes are bound to constraints to keep it more realistic.  
  hmin = 48;      
  hmax = 90;      
  wmin = 40;       
  wmax = 60;
  ////Initializing our test subjects
  for(int n = 0; n < many; n++){
    people[n] = new Person();    
    people[n].startup();
  }
  ////Place all of the random people
  for(int n = 0; n < many; n++){ 
    people[n].x = 90 + (n * 90);    
  }
  ////Set up the new array
  for (int n=0; n<many; n++) {
    bri[n]= new Person();
    bri[n].startup();
  }
  for(int n=0; n<many; n++)
  bri[n].x= (width/12)+((n*width)/(12));
  //I added a new function to the setup in order to make the buttons appear
  makebuttons();
}

//the three buttons will be put in a column on the righthand side of the screen.
void makebuttons() {
  buttons= new Button[numButtons];
  float x=150, y=50;
  for (int n=0; n<numButtons; n++) {
    buttons[n]= new Button( x, y, buttonNames[n] );
    y+=25;
  }
}  
void reset() {
  for (int n=0; n<many; n++ ) {
    //--  people[n]=  new Person( who[n] );
    people[n]=  new Person(  );
  }
  for (int n=0;n<many; n++) {
    //--  bri[n]= new Person( who[n]);
    bri[n]= new Person( );
  }
}
void draw(){
  scene();
  show();
  stats();
  raise();
  bonus( people[n], many );
  messages();
  //change();
  //clouds();
  ////draw the newly added buttons.
  for (int n=0; n<numButtons; n++) {
     buttons[n].show();
  }
}
void raise() {
  ////for each occurance of the array...
  for(int n=0; n<many; n++){            
  ////if the salary is less than 25000, they get a 20% bump up.
    if (P[n].salary<25000) {     
      salary=(P[n].salary)*1.20; 
    }     
     ////if the salary is less than 50000, but more than 25k they get a 15% bump up.
     else if (P[n].salary>25000 && P[n].salary<50000) {
      salary= (P[n].salary)*1.15;
    }
     ////if the salary is less than 75000, but more than 50000 they get a 10% bump up.
     else if ( P[n].salary>50000 && P[n].salary<75000 ) {
       salary= (P[n].salary)*1.10;
    }
     else if (P[n].salary>75000) {
       salary=(P[n].salary*1.05);
    }
  }
}


void bonus(Person p[], int m) {
  int bonus=1000;
  int salary;
  for(int n=0; n<many; n++){
    total= salary+bonus++;
    if(people[n].age<18){
      salary=salary+0;
    }
  }
}
    
////The function stats allows us to generate each indivuiduals height and weight (their statistics) 
void stats(){
  hMean();
  wMean();
}

void wMean(){
  float average = 0;
  for(int n=0; n<many; n++){
    average += people[n].weight;
  }
  average = int(average/a);
  text("Mean Weight: " + average + "lbs", (width/2)-50, (horizon *(3/2)) + 120);
}

void hMean(){
  int feet, inches;
  float average = 0;
  for(int n = 0; n < a; n++){
    average += people[n].h;
  }
  
  //Find the mean height
  average = (average / a);
  //take the individual's height and divide by 12 to get how many feet tall they are.
  feet = int(average/12);
  //the %12 lets us take the leftovers from whenever the last time that 12 went into the quotient. this gives us the inch value.
  inches = int(average%12);
  text("Mean Height: " + feet + "'" + inches + "''", (width/2)-50, (horizon *(3/2))+110);
}

void scene(){  
  noStroke();
  ////Sky
  rectMode(CORNER);
  fill(150, 200, 250);              
  rect(0,0, width, horizon);
  
  ////Ground or grass
  fill(0,255,0);
  rect(0,horizon,width,height);    
}
////DISPLAYING people////
void show(){
  for(int n = 0; n < a; n++){       
    people[n].placement();
    people[n].show();
  }
  for (int n=0; n<many;n++) {
    bri[n].placement();
    bri[n].show();
  }
}

void keyPressed(){
  if (key == 'r'){
    for(int n = 0; n < many; n++){
      people[n].startup();
      bri[n].startup();
    }
  }
  else if (key=='t') tallest(bri[], many);
  else if (key=='w') widest(bri[], many);
  else if (key=='1') raise(bri[], many);
  else if (key=='2') bonus(bri[], many);
  else if (key=='3') change(bri[], many);
}
////Find the Tallest////
void tallest( int a[], int m) {
  ////place the largest number at the end of the array
  ////swap the rest of the elements in the array to accomodate the bump to the end
  int w=whereTallest (a,m);
  int tmp;
  tmp=a[m-1];              
  a[m-1]=a[w];             
  a[w]=tmp;
}

////select the tallest
int whereTallest( int a[], int m){
  int w=0;
  for (int n=1; n<many; n++){
    if (a[n]>a[w]) w=n;
  }
}
////find the widest////
void widest( int a[], int m) {
  ////just like big, we find the fattest and we can swap all the numbers accordingly
  int w=whereWidest(a,m);
  tmp=a[m-1];              
  a[m-1]=a[w];             
  a[w]=tmp;
}
////select the widest
int whereWidest( int a[], int m){
  int w=0;
  for(int n=1; n<many; n++){
    if (a[n]>a[w]) w=n;
  }
  ////make a temp and swap them///
  int tmp;
  tmp=a[m-1];              
  a[m-1]=a[w];             
  a[w]=tmp;  
}
/*void big( int a[], int m) {
  ////place the largest number at the end of the array
  ////swap the rest of the elements in the array to accomodate the bump to the end
  int w=0;
  for (int j=1; j<m; j++) {
    if (a[j]>a[w]) w=j;
  }
  int tmp;
  tmp=a[m-1];              
  a[m-1]=a[w];             
  a[w]=tmp;
}*/
void messages(){
 textSize(10);
 text("Project 5: Precursor to the final", 25,25);
 textSize(10);
 text("AUTHOR: Brian Witte", 20, 50);
}


class Person{
  
  float r,g,b;     //colors
  float w1, w2;    //Randomize each width
  float h1, h2;    //Randomize each height
  float w,h;       //width and height
  float x,y;       //x and y position
  
  int feet, inches;
  int weight;
  float age;         //Give the age of the person
  int salary;      //How much they make
  ////Take a name from the random sample of names given. 
  String name;
  
  void startup(){
    r = random(0,255);          
    g = random(0,255);
    b = random(0,255);
    age = random(1-99);
    salary=random(1000,100000);
    w1 = random(wmin/2,wmax/2);    
    w2 = random(wmin/2,wmax/2);    
    ////the more Mean values we use in our results, will likely cause there to be less outliers and more closely applicable to real life
    h1 = random(hmin/2,hmax/2);    
    h2 = random(hmin/2,hmax/2);
    
    w = w1 + w2;  
    h = h1 + h2;
    
    name = names[int(random(0,names.length))];
  }
  
  void placement(){
    y = horizon - (h/2);  //feet stay on the ground (horizon) because the center of the body starts at horizon-.5*height)
  }
  
  void body(){
    noStroke();
    ////This will call upon the constructor to make their RGB values random each time.
    fill(r,g,b);
    rectMode(CENTER);
    //Body of person
    rect(x,y,w,h);
    ////A simple line to give the profile of the legs. This will scale with the height as well.
    stroke(0);
    line(x, h+180, x, horizon);
    //Head with a mouth and eyes
    ellipse(x, (y - (h/2) - (h/6)), w, h/3);  
    
    fill(0);
    rect(x, (y - (h/2) - (h/6)), w/5, h/6);  
    ellipse(x - w/4, (y - (h/2) - (h/4)), w/5, w/8);        
    ellipse(x + w/4, (y - (h/2) - (h/4)), w/8, w/5);
  }
  
  void show(){
    body();                 //The shape of the person
    stats();                //Persons unique traits
    messages();             //Displaying the important stuff, what makes each of them different
  }
  
  void stats(){ 
    ////Height/12= feet
    feet = int((h/12)); 
    ////The leftovers from the feet are then presented as inches
    inches = int(h % 12);
    
    weight = int(((2 * h) * w)/40);  
  }
  
  void messages(){
    textSize(10);
    text(name, x - w/2, y + h/2 + 25);
    text(feet + "'" + inches + "''",x - w/2, y + h/2 + 35);
    text(weight + "lbs", x- w/2,  y + h/2 + 45);
    text(age + "years old", x- w/2,  y + h/2 + 55);
    text("$"+salary, x- w/2,  y + h/2 + 65); 
  }
}

class Button {
  string name=" ";
  float x,y;
  float w=75, h=30;
  float r=255, g=255, b=255;
  Button(float x, float y, String name ) {
    this.name= name;
    this.x=x;
    this.y=y;
  }
  void show() {
    fill(r,g,b);
    rectMode(CENTER);
    stroke(0);
    strokeWeight(2);
    rect( x, y, w, h );
    strokeWeight(1);
    fill( 0 );
    text( name, x, y+h*2/3 );
  }
    
    //Boolean methods for testing the buttons
    boolean click(float xx, float yy){
      if(xx<x) return false;
      if(xx>x+w) return false;
      if(yy<y) return false;
      if(yy>y+h)return false;
      return true;
    }
  }


    
  
